// <auto-generated by="the Blazor I18n Text compiler" />
namespace OriinDic.I18nText
{
    public partial class Text : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "pl";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Dodaj"</summary>
        public string add;

        /// <summary>"Dodaj słowo bazowe"</summary>
        public string addBase;

        /// <summary>"Dodaj komentarz"</summary>
        public string addComment;

        /// <summary>"Komentarz dodany"</summary>
        public string addedComment;

        /// <summary>"Dodaj przykład"</summary>
        public string addExample;

        /// <summary>"Dodaj odnośnik"</summary>
        public string addLink;

        /// <summary>"Dodaj synonim"</summary>
        public string addSynonym;

        /// <summary>"Dodaj tłumaczenie"</summary>
        public string addTranslation;

        /// <summary>"Dane zanonimizowane"</summary>
        public string anonimized;

        /// <summary>"Anonimizacja"</summary>
        public string anonymize;

        /// <summary>"Wstecz"</summary>
        public string back;

        /// <summary>"Aktualny"</summary>
        public string baseTermCurrent;

        /// <summary>"Definicja"</summary>
        public string baseTermDefinition;

        /// <summary>"Przykłady"</summary>
        public string baseTermExamples;

        /// <summary>"Praca z wybranym słowem bazowym"</summary>
        public string baseTermHeader;

        /// <summary>"Język"</summary>
        public string baseTermLanguage;

        /// <summary>"Ostatnio zatwierdził"</summary>
        public string baseTermLastApproval;

        /// <summary>"Ostatnio edytował"</summary>
        public string baseTermLastEdit;

        /// <summary>"Nazwa"</summary>
        public string baseTermName;

        /// <summary>"Słowo bazowe zostało zapisane pod numerem:"</summary>
        public string baseTermSaved;

        /// <summary>"Slug"</summary>
        public string baseTermSlug;

        /// <summary>"Synonimy"</summary>
        public string baseTermSynonyms;

        /// <summary>"Anuluj"</summary>
        public string cancel;

        /// <summary>"Wyczyść filtr"</summary>
        public string clearFilter;

        /// <summary>"Data"</summary>
        public string commentDate;

        /// <summary>"Nr"</summary>
        public string commentId;

        /// <summary>"Komentarze"</summary>
        public string comments;

        /// <summary>"Tłumaczenie"</summary>
        public string commentsTranslation;

        /// <summary>"Użytkownik"</summary>
        public string commentsUser;

        /// <summary>"Tekst"</summary>
        public string commentText;

        /// <summary>"Zarządzanie językami"</summary>
        public string coordinating_languages;

        /// <summary>"Dodaj"</summary>
        public string create;

        /// <summary>"Zatwierdzone"</summary>
        public string currentTranslations;

        /// <summary>"Wysąpił błąd podczas zapisu danych."</summary>
        public string dataSavedNOk;

        /// <summary>"Dane zapisano poprawnie."</summary>
        public string dataSavedOk;

        /// <summary>"Usuń"</summary>
        public string delete;

        /// <summary>"Podczas usuwania wystąpił błąd!"</summary>
        public string deletionError;

        /// <summary>"Edytuj"</summary>
        public string edit;

        /// <summary>"Edycja słowa bazowego"</summary>
        public string editBaseTerm;

        /// <summary>"E-mail"</summary>
        public string email;

        /// <summary>"Kobieta"</summary>
        public string femaleGender;

        /// <summary>"Imię"</summary>
        public string firstname;

        /// <summary>"Płeć"</summary>
        public string gender;

        /// <summary>"Słownik pojęć z miasta Oriin"</summary>
        public string header;

        /// <summary>"Edycja słowa bazowego"</summary>
        public string headerBaseTermEdit;

        /// <summary>"Dodawanie nowego słowa bazowego"</summary>
        public string headerBaseTermNew;

        /// <summary>"Tłumaczenia"</summary>
        public string headerDashboard;

        /// <summary>"Słowniki"</summary>
        public string headerDictionaries;

        /// <summary>"Języki"</summary>
        public string headerLanguages;

        /// <summary>"Główne menu"</summary>
        public string headerMain;

        /// <summary>"Pokaż tłumaczenia"</summary>
        public string headerShowDashboard;

        /// <summary>"Pokaż języki"</summary>
        public string headerShowLanguages;

        /// <summary>"Ustawienia użytkownika"</summary>
        public string headerUser;

        /// <summary>"Cześć"</summary>
        public string hello;

        /// <summary>"Kod"</summary>
        public string langCode;

        /// <summary>"Aktualnie dostępne w systemie języki."</summary>
        public string langDesc;

        /// <summary>"Dostępne języki"</summary>
        public string langHeader;

        /// <summary>"Id"</summary>
        public string langId;

        /// <summary>"Nazwa"</summary>
        public string langName;

        /// <summary>"Znaki specjalne"</summary>
        public string langSpecialChars;

        /// <summary>"Język"</summary>
        public string language;

        /// <summary>"Nazwisko"</summary>
        public string lastname;

        /// <summary>"Słowo bazowe"</summary>
        public string linkBaseTerm;

        /// <summary>"Nr"</summary>
        public string linkId;

        /// <summary>"Odnośnik do"</summary>
        public string linkLink;

        /// <summary>"Odnośniki"</summary>
        public string links;

        /// <summary>"Tłumaczenie"</summary>
        public string linkTranslation;

        /// <summary>"Dane wczytane"</summary>
        public string loaded;

        /// <summary>"Wczytano wierszy:"</summary>
        public string loadedNrRows;

        /// <summary>"Wczytuję dane - proszę czekać.."</summary>
        public string loading;

        /// <summary>"Zaloguj się"</summary>
        public string logIn;

        /// <summary>"Zaloguj się"</summary>
        public string loginButton;

        /// <summary>"Błąd w logowaniu. Sprawdź nazwę użytkownika i/lub hasło."</summary>
        public string loginError;

        /// <summary>"Logowanie do serwisu"</summary>
        public string loginHeader;

        /// <summary>"Użytkownik"</summary>
        public string loginName;

        /// <summary>"Hasło"</summary>
        public string loginPassword;

        /// <summary>"Pozwala na uzyskanie odpowiednich uprawnień"</summary>
        public string loginSubtitle;

        /// <summary>"Zalogowanie poprawnie"</summary>
        public string loginSuccess;

        /// <summary>"Wyloguj się"</summary>
        public string logOut;

        /// <summary>"Mężczyzna"</summary>
        public string maleGender;

        /// <summary>"Nowy"</summary>
        public string newTxt;

        /// <summary>"Następna"</summary>
        public string next;

        /// <summary>"Brak nazwy słowa bazowego - aktualizuj"</summary>
        public string noBaseTermName;

        /// <summary>"Brak danych"</summary>
        public string noData;

        /// <summary>"-"</summary>
        public string noGender;

        /// <summary>"Brak wyników!"</summary>
        public string noResults;

        /// <summary>"Brak nazwy tłumaczenia - aktualizuj"</summary>
        public string noTranslationName;

        /// <summary>"Nie ustawiony"</summary>
        public string notSet;

        /// <summary>"Dane"</summary>
        public string personalData;

        /// <summary>"Dane"</summary>
        public string personalDataHeader;

        /// <summary>"Personalne dane użytkownika"</summary>
        public string personalDataSubtitle;

        /// <summary>"Ustawienia"</summary>
        public string personalSettings;

        /// <summary>"Poprzednia"</summary>
        public string previous;

        /// <summary>"Przywróć"</summary>
        public string reset;

        /// <summary>"Wierszy na stronie"</summary>
        public string rowsPerPage;

        /// <summary>"Zapisz"</summary>
        public string save;

        /// <summary>"Błąd w zapisie. Sprawdź dane."</summary>
        public string saveError;

        /// <summary>"Szukaj"</summary>
        public string search;

        /// <summary>"Szukam:"</summary>
        public string searchTitle;

        /// <summary>"Aktualny język bazowy"</summary>
        public string settingsCurrentLang;

        /// <summary>"Ustawienia"</summary>
        public string settingsHeader;

        /// <summary>"Ustawienia użytkownika"</summary>
        public string settingsSubtitle;

        /// <summary>"Słownik Oriin"</summary>
        public string shortHeader;

        /// <summary>"Coś nie działa?"</summary>
        public string somethingWrong;

        /// <summary>"Wypowiedz"</summary>
        public string speech;

        /// <summary>"Super User ma dostęp do wszystkich ustawień"</summary>
        public string superUserHasAll;

        /// <summary>"Termin"</summary>
        public string termTitle;

        /// <summary>"Języki do tłumaczenia"</summary>
        public string translating_languages;

        /// <summary>"Aktualny"</summary>
        public string translationCurrent;

        /// <summary>"Definicja"</summary>
        public string translationDefinition;

        /// <summary>"Przykłady"</summary>
        public string translationExamples;

        /// <summary>"Praca z wybranym tłumaczeniem"</summary>
        public string translationHeader;

        /// <summary>"Język"</summary>
        public string translationLanguage;

        /// <summary>"Ostatnio zatwierdził"</summary>
        public string translationLastApproval;

        /// <summary>"Ostatnio edytował"</summary>
        public string translationLastEdit;

        /// <summary>"Nazwa"</summary>
        public string translationName;

        /// <summary>"Tłumaczenie zostało zapisane pod numerem:"</summary>
        public string translationSaved;

        /// <summary>"Synonimy"</summary>
        public string translationSynonyms;

        /// <summary>"Tłumaczenie"</summary>
        public string translationTitle;

        /// <summary>"Dane zaktualizowane"</summary>
        public string updated;

        /// <summary>"Podczas usuwania konta użytkownika wystąpił błąd!"</summary>
        public string userDeletionError;

        /// <summary>"Użytkownik"</summary>
        public string username;

        /// <summary>"Użytkownicy"</summary>
        public string users;

        /// <summary>"Koordynowane języki"</summary>
        public string usersCoordinatingLanguages;

        /// <summary>"E-mail użytkownika"</summary>
        public string usersEmail;

        /// <summary>"Imię użytkownika"</summary>
        public string usersFirstName;

        /// <summary>"Nr"</summary>
        public string usersId;

        /// <summary>"Asystent"</summary>
        public string usersIsAssistant;

        /// <summary>"Super użytkownik"</summary>
        public string usersIsSuperUser;

        /// <summary>"Nazwisko użytkownika"</summary>
        public string usersLastName;

        /// <summary>"Tłumaczone języki"</summary>
        public string usersTranslatingLanguages;

        /// <summary>"Nazwa użytkownika"</summary>
        public string usersUserName;

        /// <summary>"Przyznane Ci role:"</summary>
        public string yourRoles;

        /// <summary>"Twoje konto zostały usunięte!"</summary>
        public string youWhereDeleted;
    }
}
