// <auto-generated by="the Blazor I18n Text compiler" />
namespace OriinDic.I18nText
{
    public partial class Text : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "pl";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Dodaj"</summary>
        public string Add;

        /// <summary>"Dodaj słowo bazowe"</summary>
        public string AddBase;

        /// <summary>"Dodaj komentarz"</summary>
        public string AddComment;

        /// <summary>"Komentarz dodany"</summary>
        public string AddedComment;

        /// <summary>"Dodaj przykład"</summary>
        public string AddExample;

        /// <summary>"Dodaj odnośnik"</summary>
        public string AddLink;

        /// <summary>"Dodaj synonim"</summary>
        public string AddSynonym;

        /// <summary>"Dodaj tłumaczenie"</summary>
        public string AddTranslation;

        /// <summary>"Anonimizacja"</summary>
        public string Anonymize;

        /// <summary>"Dane zanonimizowane"</summary>
        public string Anonymized;

        /// <summary>"Zatwierdzone"</summary>
        public string Approved;

        /// <summary>"Wstecz"</summary>
        public string Back;

        /// <summary>"Aktualny"</summary>
        public string BaseTermCurrent;

        /// <summary>"Definicja"</summary>
        public string BaseTermDefinition;

        /// <summary>"Przykłady"</summary>
        public string BaseTermExamples;

        /// <summary>"Praca z wybranym słowem bazowym"</summary>
        public string BaseTermHeader;

        /// <summary>"Język"</summary>
        public string BaseTermLanguage;

        /// <summary>"Ostatnio zatwierdził"</summary>
        public string BaseTermLastApproval;

        /// <summary>"Ostatnio edytował"</summary>
        public string BaseTermLastEdit;

        /// <summary>"Nazwa"</summary>
        public string BaseTermName;

        /// <summary>"Słowo bazowe zostało zapisane pod numerem:"</summary>
        public string BaseTermSaved;

        /// <summary>"Slug"</summary>
        public string BaseTermSlug;

        /// <summary>"Synonimy"</summary>
        public string BaseTermSynonyms;

        /// <summary>"Anuluj"</summary>
        public string Cancel;

        /// <summary>"Wyczyść filtr"</summary>
        public string ClearFilter;

        /// <summary>"Data"</summary>
        public string CommentDate;

        /// <summary>"Nr"</summary>
        public string CommentId;

        /// <summary>"Komentarze"</summary>
        public string Comments;

        /// <summary>"Tłumaczenie"</summary>
        public string CommentsTranslation;

        /// <summary>"Użytkownik"</summary>
        public string CommentsUser;

        /// <summary>"Tekst"</summary>
        public string CommentText;

        /// <summary>"Zarządzanie językami"</summary>
        public string CoordinatingLanguages;

        /// <summary>"Dodaj"</summary>
        public string Create;

        /// <summary>"Zatwierdzone"</summary>
        public string CurrentTranslations;

        /// <summary>"Wysąpił błąd podczas zapisu danych."</summary>
        public string DataSavedNOk;

        /// <summary>"Dane zapisano poprawnie."</summary>
        public string DataSavedOk;

        /// <summary>"Usuń"</summary>
        public string Delete;

        /// <summary>"Podczas usuwania wystąpił błąd!"</summary>
        public string DeletionError;

        /// <summary>"Edytuj"</summary>
        public string Edit;

        /// <summary>"Edycja słowa bazowego"</summary>
        public string EditBaseTerm;

        /// <summary>"E-mail"</summary>
        public string Email;

        /// <summary>"Kobieta"</summary>
        public string FemaleGender;

        /// <summary>"Imię"</summary>
        public string FirstName;

        /// <summary>"Płeć"</summary>
        public string Gender;

        /// <summary>"Słownik pojęć z miasta Oriin"</summary>
        public string Header;

        /// <summary>"Edycja słowa bazowego"</summary>
        public string HeaderBaseTermEdit;

        /// <summary>"Dodawanie nowego słowa bazowego"</summary>
        public string HeaderBaseTermNew;

        /// <summary>"Tłumaczenia"</summary>
        public string HeaderDashboard;

        /// <summary>"Słowniki"</summary>
        public string HeaderDictionaries;

        /// <summary>"Języki"</summary>
        public string HeaderLanguages;

        /// <summary>"Główne menu"</summary>
        public string HeaderMain;

        /// <summary>"Pokaż słowa bazowe"</summary>
        public string HeaderShowDashboardBase;

        /// <summary>"Pokaż tłumaczenia"</summary>
        public string HeaderShowDashboardTrans;

        /// <summary>"Pokaż języki"</summary>
        public string HeaderShowLanguages;

        /// <summary>"Ustawienia użytkownika"</summary>
        public string HeaderUser;

        /// <summary>"Cześć"</summary>
        public string Hello;

        /// <summary>"Kod"</summary>
        public string LangCode;

        /// <summary>"Aktualnie dostępne w systemie języki."</summary>
        public string LangDesc;

        /// <summary>"Dostępne języki"</summary>
        public string LangHeader;

        /// <summary>"Id"</summary>
        public string LangId;

        /// <summary>"Nazwa"</summary>
        public string LangName;

        /// <summary>"Znaki specjalne"</summary>
        public string LangSpecialChars;

        /// <summary>"Język"</summary>
        public string Language;

        /// <summary>"Nazwisko"</summary>
        public string LastName;

        /// <summary>"Słowo bazowe"</summary>
        public string LinkBaseTerm;

        /// <summary>"Nr"</summary>
        public string LinkId;

        /// <summary>"Odnośnik do"</summary>
        public string LinkLink;

        /// <summary>"Odnośniki"</summary>
        public string Links;

        /// <summary>"Tłumaczenie"</summary>
        public string LinkTranslation;

        /// <summary>"Dane wczytane"</summary>
        public string Loaded;

        /// <summary>"Wczytano wierszy:"</summary>
        public string LoadedNrRows;

        /// <summary>"Wczytuję dane - proszę czekać.."</summary>
        public string Loading;

        /// <summary>"Zaloguj się"</summary>
        public string LogIn;

        /// <summary>"Zaloguj się"</summary>
        public string LoginButton;

        /// <summary>"Błąd w logowaniu. Sprawdź nazwę użytkownika i/lub hasło."</summary>
        public string LoginError;

        /// <summary>"Logowanie do serwisu"</summary>
        public string LoginHeader;

        /// <summary>"Użytkownik"</summary>
        public string LoginName;

        /// <summary>"Hasło"</summary>
        public string LoginPassword;

        /// <summary>"Pozwala na uzyskanie odpowiednich uprawnień"</summary>
        public string LoginSubtitle;

        /// <summary>"Zalogowanie poprawnie"</summary>
        public string LoginSuccess;

        /// <summary>"Wyloguj się"</summary>
        public string LogOut;

        /// <summary>"Mężczyzna"</summary>
        public string MaleGender;

        /// <summary>"Nowy"</summary>
        public string NewTxt;

        /// <summary>"Następna"</summary>
        public string Next;

        /// <summary>"Brak nazwy słowa bazowego - aktualizuj"</summary>
        public string NoBaseTermName;

        /// <summary>"Brak danych"</summary>
        public string NoData;

        /// <summary>"-"</summary>
        public string NoGender;

        /// <summary>"Brak wyników!"</summary>
        public string NoResults;

        /// <summary>"Brak nazwy tłumaczenia - aktualizuj"</summary>
        public string NoTranslationName;

        /// <summary>"Nie ustawiony"</summary>
        public string NotSet;

        /// <summary>"Dane"</summary>
        public string PersonalData;

        /// <summary>"Dane"</summary>
        public string PersonalDataHeader;

        /// <summary>"Personalne dane użytkownika"</summary>
        public string PersonalDataSubtitle;

        /// <summary>"Ustawienia"</summary>
        public string PersonalSettings;

        /// <summary>"Poprzednia"</summary>
        public string Previous;

        /// <summary>"Przywróć"</summary>
        public string Reset;

        /// <summary>"Wierszy na stronie"</summary>
        public string RowsPerPage;

        /// <summary>"Zapisz"</summary>
        public string Save;

        /// <summary>"Błąd w zapisie. Sprawdź dane."</summary>
        public string SaveError;

        /// <summary>"Szukaj"</summary>
        public string Search;

        /// <summary>"Szukam:"</summary>
        public string SearchTitle;

        /// <summary>"Aktualny język bazowy"</summary>
        public string SettingsCurrentLang;

        /// <summary>"Ustawienia"</summary>
        public string SettingsHeader;

        /// <summary>"Ustawienia użytkownika"</summary>
        public string SettingsSubtitle;

        /// <summary>"Słownik Oriin"</summary>
        public string ShortHeader;

        /// <summary>"Coś nie działa?"</summary>
        public string SomethingWrong;

        /// <summary>"Wypowiedz"</summary>
        public string Speech;

        /// <summary>"Super User ma dostęp do wszystkich ustawień"</summary>
        public string SuperUserHasAll;

        /// <summary>"Termin"</summary>
        public string TermTitle;

        /// <summary>"Języki do tłumaczenia"</summary>
        public string TranslatingLanguages;

        /// <summary>"Zatwierdź"</summary>
        public string TranslationApproval;

        /// <summary>"Aktualny"</summary>
        public string TranslationCurrent;

        /// <summary>"Definicja"</summary>
        public string TranslationDefinition;

        /// <summary>"Przykłady"</summary>
        public string TranslationExamples;

        /// <summary>"Praca z wybranym tłumaczeniem"</summary>
        public string TranslationHeader;

        /// <summary>"Język"</summary>
        public string TranslationLanguage;

        /// <summary>"Ostatnio zatwierdził"</summary>
        public string TranslationLastApproval;

        /// <summary>"Ostatnio edytował"</summary>
        public string TranslationLastEdit;

        /// <summary>"Nazwa"</summary>
        public string TranslationName;

        /// <summary>"Tłumaczenie zostało zapisane pod numerem:"</summary>
        public string TranslationSaved;

        /// <summary>"Synonimy"</summary>
        public string TranslationSynonyms;

        /// <summary>"Tłumaczenie"</summary>
        public string TranslationTitle;

        /// <summary>"Dane zaktualizowane"</summary>
        public string Updated;

        /// <summary>"Podczas usuwania konta użytkownika wystąpił błąd!"</summary>
        public string UserDeletionError;

        /// <summary>"Użytkownik"</summary>
        public string UserName;

        /// <summary>"Użytkownicy"</summary>
        public string Users;

        /// <summary>"Koordynowane języki"</summary>
        public string UsersCoordinatingLanguages;

        /// <summary>"E-mail użytkownika"</summary>
        public string UsersEmail;

        /// <summary>"Imię użytkownika"</summary>
        public string UsersFirstName;

        /// <summary>"Nr"</summary>
        public string UsersId;

        /// <summary>"Asystent"</summary>
        public string UsersIsAssistant;

        /// <summary>"Super użytkownik"</summary>
        public string UsersIsSuperUser;

        /// <summary>"Nazwisko użytkownika"</summary>
        public string UsersLastName;

        /// <summary>"Tłumaczone języki"</summary>
        public string UsersTranslatingLanguages;

        /// <summary>"Nazwa użytkownika"</summary>
        public string UsersUserName;

        /// <summary>"Przyznane Ci role:"</summary>
        public string YourRoles;

        /// <summary>"Twoje konto zostały usunięte!"</summary>
        public string YouWhereDeleted;
    }
}
