// <auto-generated by="the Blazor I18n Text compiler" />
namespace OriinDic.I18nText
{
    public partial class Text : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "pl";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Dodaj"</summary>
        public string Add;

        /// <summary>"Dodaj słowo bazowe"</summary>
        public string AddBase;

        /// <summary>"Dodaj komentarz"</summary>
        public string AddComment;

        /// <summary>"Komentarz dodany"</summary>
        public string AddedComment;

        /// <summary>"Dodano odnośnik"</summary>
        public string AddedLink;

        /// <summary>"Użytkownik dodany"</summary>
        public string AddedUser;

        /// <summary>"Dodaj przykład"</summary>
        public string AddExample;

        /// <summary>"Dodaj odnośnik"</summary>
        public string AddLink;

        /// <summary>"Dodaj synonim"</summary>
        public string AddSynonym;

        /// <summary>"Dodaj tłumaczenie"</summary>
        public string AddTranslation;

        /// <summary>"Anonimizacja"</summary>
        public string Anonymize;

        /// <summary>"Dane zanonimizowane"</summary>
        public string Anonymized;

        /// <summary>"Zatwierdzone"</summary>
        public string Approved;

        /// <summary>"Wstecz"</summary>
        public string Back;

        /// <summary>"Aktualny"</summary>
        public string BaseTermCurrent;

        /// <summary>"Definicja"</summary>
        public string BaseTermDefinition;

        /// <summary>"Definicja nie może być pusta - proszę wpisać conajmniej kilka znaków"</summary>
        public string BaseTermDefinitionError;

        /// <summary>"Definicja słowa lub zdania"</summary>
        public string BaseTermDefinitionHelp;

        /// <summary>"Przykłady"</summary>
        public string BaseTermExamples;

        /// <summary>"Praca z wybranym słowem bazowym"</summary>
        public string BaseTermHeader;

        /// <summary>"Język"</summary>
        public string BaseTermLanguage;

        /// <summary>"Ostatnio zatwierdził"</summary>
        public string BaseTermLastApproval;

        /// <summary>"Ostatnio edytował"</summary>
        public string BaseTermLastEdit;

        /// <summary>"Nazwa"</summary>
        public string BaseTermName;

        /// <summary>"Słowo lub zdanie nie może być puste - proszę wpisać conajmniej kilka znaków"</summary>
        public string BaseTermNameError;

        /// <summary>"Słowo lub zdanie które podlega tłumaczeniu"</summary>
        public string BaseTermNameHelp;

        /// <summary>"brak"</summary>
        public string BaseTermNone;

        /// <summary>"Słowo bazowe zostało zapisane pod numerem:"</summary>
        public string BaseTermSaved;

        /// <summary>"Slug"</summary>
        public string BaseTermSlug;

        /// <summary>"Synonimy"</summary>
        public string BaseTermSynonyms;

        /// <summary>"Bez tłumaczeń"</summary>
        public string BaseTermWithoutTranslations;

        /// <summary>"Z tłumaczeniami"</summary>
        public string BaseTermWithTranslations;

        /// <summary>"Anuluj"</summary>
        public string Cancel;

        /// <summary>"Wyczyść filtr"</summary>
        public string ClearFilter;

        /// <summary>"Komentarz nie może być pusty"</summary>
        public string CommentAddError;

        /// <summary>"Dodaj nowy komentarz wpisując go powyżej"</summary>
        public string CommentAddHelp;

        /// <summary>"Data"</summary>
        public string CommentDate;

        /// <summary>"Nr"</summary>
        public string CommentId;

        /// <summary>"Komentarze"</summary>
        public string Comments;

        /// <summary>"Tłumaczenie"</summary>
        public string CommentsTranslation;

        /// <summary>"Użytkownik"</summary>
        public string CommentsUser;

        /// <summary>"Tekst"</summary>
        public string CommentText;

        /// <summary>"Potwierdź"</summary>
        public string Confirm;

        /// <summary>"Zarządzanie językami"</summary>
        public string CoordinatingLanguages;

        /// <summary>"Dodaj"</summary>
        public string Create;

        /// <summary>"Aktualne hasło"</summary>
        public string CurrentPassword;

        /// <summary>"Musisz wprowadzić hasło o długości co najmniej 6 znaków"</summary>
        public string CurrentPasswordError;

        /// <summary>"Wprowadź aktualne hasło"</summary>
        public string CurrentPasswordHelp;

        /// <summary>"Zatwierdzone"</summary>
        public string CurrentTranslations;

        /// <summary>"Pokazuje tylko już zatwierdzone tłumaczenia (nie pokazuje innych wersji)"</summary>
        public string CurrentTranslationsHelp;

        /// <summary>"Wysąpił błąd podczas zapisu danych."</summary>
        public string DataSavedNOk;

        /// <summary>"Dane zapisano poprawnie."</summary>
        public string DataSavedOk;

        /// <summary>"Usuń"</summary>
        public string Delete;

        /// <summary>"Dane usunięto"</summary>
        public string Deleted;

        /// <summary>"Podczas usuwania wystąpił błąd!"</summary>
        public string DeletionError;

        /// <summary>"Edytuj"</summary>
        public string Edit;

        /// <summary>"Edycja słowa bazowego"</summary>
        public string EditBaseTerm;

        /// <summary>"E-mail"</summary>
        public string Email;

        /// <summary>"Wprowadzony tekst musi być adresem e-mail"</summary>
        public string EmailError;

        /// <summary>"Kobieta"</summary>
        public string FemaleGender;

        /// <summary>"Imię"</summary>
        public string FirstName;

        /// <summary>"na podstawie Akademii Wiedzy Duchowej Zbigniewa Jana Popko"</summary>
        public string FromJanPopko;

        /// <summary>"Płeć"</summary>
        public string Gender;

        /// <summary>"SŁOWNIK WIEDZY DUCHOWEJ z miasta Oriin"</summary>
        public string Header;

        /// <summary>"Edycja słowa bazowego"</summary>
        public string HeaderBaseTermEdit;

        /// <summary>"Dodawanie nowego słowa bazowego"</summary>
        public string HeaderBaseTermNew;

        /// <summary>"Tłumaczenia"</summary>
        public string HeaderDashboard;

        /// <summary>"Słowniki"</summary>
        public string HeaderDictionaries;

        /// <summary>"Języki"</summary>
        public string HeaderLanguages;

        /// <summary>"Główne menu"</summary>
        public string HeaderMain;

        /// <summary>"Szukaj słów bazowych i tłumaczeń"</summary>
        public string HeaderShowDashboard;

        /// <summary>"Szukaj słów bazowych"</summary>
        public string HeaderShowDashboardBase;

        /// <summary>"Szukaj tłumaczeń"</summary>
        public string HeaderShowDashboardTrans;

        /// <summary>"Pokaż języki"</summary>
        public string HeaderShowLanguages;

        /// <summary>"Ustawienia użytkownika"</summary>
        public string HeaderUser;

        /// <summary>"DICTIONARY OF SPIRITUAL KNOWLEDGE from the city of Oriin"</summary>
        public string Headline;

        /// <summary>"Cześć"</summary>
        public string Hello;

        /// <summary>"Kod"</summary>
        public string LangCode;

        /// <summary>"Aktualnie dostępne w systemie języki."</summary>
        public string LangDesc;

        /// <summary>"Dostępne języki"</summary>
        public string LangHeader;

        /// <summary>"Id"</summary>
        public string LangId;

        /// <summary>"Nazwa"</summary>
        public string LangName;

        /// <summary>"Znaki specjalne"</summary>
        public string LangSpecialChars;

        /// <summary>"Język"</summary>
        public string Language;

        /// <summary>"Nazwisko"</summary>
        public string LastName;

        /// <summary>"Słowo bazowe"</summary>
        public string LinkBaseTerm;

        /// <summary>"Nr"</summary>
        public string LinkId;

        /// <summary>"Odnośnik do"</summary>
        public string LinkLink;

        /// <summary>"Odnośniki"</summary>
        public string Links;

        /// <summary>"Tłumaczenie"</summary>
        public string LinkTranslation;

        /// <summary>"Dane wczytane"</summary>
        public string Loaded;

        /// <summary>"Wczytano wierszy:"</summary>
        public string LoadedNrRows;

        /// <summary>"Wczytuję dane - proszę czekać.."</summary>
        public string Loading;

        /// <summary>"Login"</summary>
        public string Login;

        /// <summary>"Zaloguj się"</summary>
        public string LogIn;

        /// <summary>"Zaloguj się"</summary>
        public string LoginButton;

        /// <summary>"Błąd w logowaniu. Sprawdź nazwę użytkownika i/lub hasło."</summary>
        public string LoginError;

        /// <summary>"Logowanie do serwisu"</summary>
        public string LoginHeader;

        /// <summary>"Użytkownik"</summary>
        public string LoginName;

        /// <summary>"Hasło"</summary>
        public string LoginPassword;

        /// <summary>"Pozwala na uzyskanie odpowiednich uprawnień"</summary>
        public string LoginSubtitle;

        /// <summary>"Zalogowanie poprawnie"</summary>
        public string LoginSuccess;

        /// <summary>"Wyloguj się"</summary>
        public string LogOut;

        /// <summary>"Mężczyzna"</summary>
        public string MaleGender;

        /// <summary>"Nowe hasło"</summary>
        public string NewPassword;

        /// <summary>"Musisz wprowadzić nowe hasło o długości co najmniej 6 znaków"</summary>
        public string NewPasswordError;

        /// <summary>"Wprowadź nowe hasło"</summary>
        public string NewPasswordHelp;

        /// <summary>"Nowy"</summary>
        public string NewTxt;

        /// <summary>"Następna"</summary>
        public string Next;

        /// <summary>"Brak nazwy słowa bazowego - aktualizuj"</summary>
        public string NoBaseTermName;

        /// <summary>"Brak danych"</summary>
        public string NoData;

        /// <summary>"-"</summary>
        public string NoGender;

        /// <summary>"Brak wyników!"</summary>
        public string NoResults;

        /// <summary>"Brak nazwy tłumaczenia - aktualizuj"</summary>
        public string NoTranslationName;

        /// <summary>"Nie ustawiony"</summary>
        public string NotSet;

        /// <summary>"Zmiana hasła"</summary>
        public string PasswordChange;

        /// <summary>"Musisz wprowadzić hasło o długości co najmniej 6 znaków"</summary>
        public string PasswordError;

        /// <summary>"Proszę wprowadzić hasło"</summary>
        public string PasswordHelp;

        /// <summary>"Reset hasła"</summary>
        public string PasswordReset;

        /// <summary>"Password reset completed successfully."</summary>
        public string PasswordReseted;

        /// <summary>"Reset hasła wysłany - proszę sprawdź email, by przejść do następnych kroków."</summary>
        public string PasswordResetSend;

        /// <summary>"Dane"</summary>
        public string PersonalData;

        /// <summary>"Dane"</summary>
        public string PersonalDataHeader;

        /// <summary>"Personalne dane użytkownika"</summary>
        public string PersonalDataSubtitle;

        /// <summary>"Ustawienia"</summary>
        public string PersonalSettings;

        /// <summary>"Poprzednia"</summary>
        public string Previous;

        /// <summary>"Profil"</summary>
        public string Profile;

        /// <summary>"Powtórz nowe hasło"</summary>
        public string ReNewPassword;

        /// <summary>"Musisz ponownie wprowadzić to samo nowe hasło"</summary>
        public string ReNewPasswordError;

        /// <summary>"Wprowadź ponownie nowe hasło"</summary>
        public string ReNewPasswordHelp;

        /// <summary>"Przywróć"</summary>
        public string Reset;

        /// <summary>"Wierszy na stronie"</summary>
        public string RowsPerPage;

        /// <summary>"Proszę wprowadzić maksymalną ilość wierszy na stronie"</summary>
        public string RowsPerPageHelp;

        /// <summary>"Zapisz"</summary>
        public string Save;

        /// <summary>"Błąd w zapisie. Sprawdź dane."</summary>
        public string SaveError;

        /// <summary>"Szukaj"</summary>
        public string Search;

        /// <summary>"Szukam:"</summary>
        public string SearchTitle;

        /// <summary>"Aktualny język bazowy"</summary>
        public string SettingsCurrentLang;

        /// <summary>"Wskazuje jaki jezyk jest językiem bazowym. Na razie wspieranym jest tylko polski jako bazowy."</summary>
        public string SettingsCurrentLangHelp;

        /// <summary>"Ustawienia"</summary>
        public string SettingsHeader;

        /// <summary>"Ustawienia użytkownika"</summary>
        public string SettingsSubtitle;

        /// <summary>"Skórka włączona"</summary>
        public string SettingsThemeEnabled;

        /// <summary>"Oznacza czy skórka aplikacji zawierająca ustawienia wyglądu jest włączona i czy zmieniać pozostałe ustawienia."</summary>
        public string SettingsThemeEnabledHelp;

        /// <summary>"Kolor główny"</summary>
        public string SettingsThemePrimaryColor;

        /// <summary>"Główny kolor wiodący dla przycisków"</summary>
        public string SettingsThemePrimaryColorHelp;

        /// <summary>"Elementy zaokrąglane"</summary>
        public string SettingsThemeRoundedElements;

        /// <summary>"Po włączeniu na stronie będą przyciski posiadały zaokrąglone krawędzie."</summary>
        public string SettingsThemeRoundedElementsHelp;

        /// <summary>"SŁOWNIK"</summary>
        public string ShortHeader2;

        /// <summary>"Coś nie działa?"</summary>
        public string SomethingWrong;

        /// <summary>"Wypowiedz"</summary>
        public string Speech;

        /// <summary>"Super User ma dostęp do wszystkich ustawień"</summary>
        public string SuperUserHasAll;

        /// <summary>"Termin"</summary>
        public string TermTitle;

        /// <summary>"Języki do tłumaczenia"</summary>
        public string TranslatingLanguages;

        /// <summary>"Dodano tłumaczenie"</summary>
        public string TranslationAdded;

        /// <summary>"Zatwierdź"</summary>
        public string TranslationApproval;

        /// <summary>"Tłumaczenie zatwierdzono"</summary>
        public string TranslationApproved;

        /// <summary>"Aktualny"</summary>
        public string TranslationCurrent;

        /// <summary>"Zaznaczenie tego pola oznacza czy tłumaczenie jest głównym obowiązującym tłumaczeniem"</summary>
        public string TranslationCurrentHelp;

        /// <summary>"Definicja"</summary>
        public string TranslationDefinition;

        /// <summary>"Definicja tłumaczonego słowa lub zdania"</summary>
        public string TranslationDefinitionHelp;

        /// <summary>"Przykłady"</summary>
        public string TranslationExamples;

        /// <summary>"Praca z wybranym tłumaczeniem"</summary>
        public string TranslationHeader;

        /// <summary>"Język"</summary>
        public string TranslationLanguage;

        /// <summary>"Ostatnio zatwierdził"</summary>
        public string TranslationLastApproval;

        /// <summary>"Ostatnio edytował"</summary>
        public string TranslationLastEdit;

        /// <summary>"Nazwa"</summary>
        public string TranslationName;

        /// <summary>"Tłumaczenie słowa lub zdania nie może być puste - proszę wpisać conajminej kilka znaków"</summary>
        public string TranslationNameError;

        /// <summary>"Tłumaczenie słowa lub zdania"</summary>
        public string TranslationNameHelp;

        /// <summary>"Tłumaczenie zostało zapisane pod numerem:"</summary>
        public string TranslationSaved;

        /// <summary>"Synonimy"</summary>
        public string TranslationSynonyms;

        /// <summary>"Tłumaczenie"</summary>
        public string TranslationTitle;

        /// <summary>"Dane zaktualizowane"</summary>
        public string Updated;

        /// <summary>"Podczas usuwania konta użytkownika wystąpił błąd!"</summary>
        public string UserDeletionError;

        /// <summary>"Proszę podać zarejestrowany już adres e-mail, na który ma zostać wysłana instrukcja resetowania hasła"</summary>
        public string UserEmailResetHelp;

        /// <summary>"Użytkownik"</summary>
        public string UserName;

        /// <summary>"Pole nazwy użytkownika nie może być puste"</summary>
        public string UserNameError;

        /// <summary>"Wprowadź swoją nazwę użytkownika, aby uzyskać dostęp do tego systemu"</summary>
        public string UserNameHelp;

        /// <summary>"Użytkownicy"</summary>
        public string Users;

        /// <summary>"Koordynowane języki"</summary>
        public string UsersCoordinatingLanguages;

        /// <summary>"E-mail użytkownika"</summary>
        public string UsersEmail;

        /// <summary>"Imię użytkownika"</summary>
        public string UsersFirstName;

        /// <summary>"Nr"</summary>
        public string UsersId;

        /// <summary>"Asystent"</summary>
        public string UsersIsAssistant;

        /// <summary>"Super użytkownik"</summary>
        public string UsersIsSuperUser;

        /// <summary>"Nazwisko użytkownika"</summary>
        public string UsersLastName;

        /// <summary>"Tłumaczone języki"</summary>
        public string UsersTranslatingLanguages;

        /// <summary>"Nazwa użytkownika"</summary>
        public string UsersUserName;

        /// <summary>"Przyznane Ci role:"</summary>
        public string YourRoles;

        /// <summary>"Twoje konto zostały usunięte!"</summary>
        public string YouWhereDeleted;
    }
}
