name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
      with:
          persist-credentials: false
           
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100-preview.6.21355.2'

    - name: Publish with dotnet
      run: dotnet publish --configuration Release --output build
    
      
    - name: Publish to server
      id: deploy_with_scp
      uses: noobly314/deploy-with-scp@v1
      with:
        src: /build
        dest: /home/oriin/front/bin/Release/net6.0/publish/wwwroot
        username: ${{ secrets.SERVER_USER }}
        server-ip: ${{ secrets.SERVER_IP }}
        password: ${{ secrets.SERVER_PASSWORD }} 
        
